services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${db_port}:5432
    environment:
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_pass}
      POSTGRES_DB: ${db_name}

  web:
    image: ssuhotskiy/cheat_sheets:v1.1
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data: